@startuml FactoryMastery Entity Relationship Diagram

' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

entity User {
  id: ObjectId
  email: String <<limit: 255>>
  username: String <<limit: 255>>
  encryptedPassword: String <<limit: 255, default: "", null: false>>
  firstName: String <<limit: 255>>
  lastName: String <<limit: 255>>
  fullName: String
  image: String <<limit: 255>>
  authRole: String
  tokens: String <<limit: 65535>>
  disabled: Boolean <<default: false>>
  isResetPassword: Boolean
  isMessageFullAccess: Boolean
  isReportTool: Boolean
  resetPasswordToken: String <<limit: 255>>
  resetPasswordSentAt: DateTime
  signInCount: int <<limit: 4, default: 0, null: false>>
  currentSignInAt: DateTime
  lastSignInAt: DateTime
  organizationId: ObjectId
  createdAt: DateTime
  updatedAt: DateTime
}

entity Organization {
  id: ObjectId
  name: String <<limit: 255>>
  license: String <<limit: 255>>
  trialExpirationDate: DateTime
  status: int <<limit: 4, default: 2>>
  subdomain: String <<limit: 255>>
  role: String <<limit: 255>>
  publicProcessUrl: String <<limit: 255>>
  image: String <<limit: 255>>
  logo: String <<limit: 255>>
  dashboardBannerText: String <<limit: 65535>>
  horizontalLogo: String <<limit: 255>>
  welcomeMessageContent: String <<limit: 65535>>
  welcomeMessageText: String <<limit: 255>>
  welcomeMessageImage: String <<limit: 255>>
  isLightSideBar: Boolean <<default: false, null: false>>
  sidebarIconColor: int <<limit: 4, default: 0>>
  isThemeSetting: Boolean <<default: false>>
  isModularProcess: Boolean <<default: false>>
  isReportTool: Boolean <<default: false>>
  isCollectionFeature: Boolean <<default: false>>
  createdAt: DateTime <<null: false>>
  updatedAt: DateTime <<null: false>>
}

entity Group {
  id: ObjectId
  name: String <<limit: 255>>
  description: String <<limit: 65535>>
  isCompanyGroup: Boolean <<default: false>>
  archived: Boolean <<default: false>>
  deleted: Boolean <<default: false>>
  organizationId: ObjectId
  collectionId: ObjectId
  createdAt: DateTime <<null: false>>
  updatedAt: DateTime <<null: false>>
}

entity GroupMember {
  id: ObjectId
  permission: String
  groupId: ObjectId
  userId: ObjectId
  createdAt: DateTime <<null: false>>
  updatedAt: DateTime <<null: false>>
}

entity GroupMessage {
  id: ObjectId
  content: String
  attachments: Attachment[]
  groupThreadId: ObjectId
  userId: ObjectId
  receiverId: ObjectId
  createdAt: DateTime <<null: false>>
  updatedAt: DateTime <<null: false>>
}

entity SupportMessage {
  id: ObjectId
  content: String
  attachments: Attachment[]
  supportThreadId: ObjectId
  userId: ObjectId
  createdAt: DateTime <<null: false>>
  updatedAt: DateTime <<null: false>>
}

entity Attachment {
  url: String
  name: String
  type: String
  groupMessageId: ObjectId
  supportMessageId: ObjectId
}

entity GroupMessageThread {
  id: ObjectId
  name: String
  isPrivate: Boolean
  organizationId: ObjectId
  lastMessageAt: DateTime
  createdAt: DateTime <<null: false>>
  updatedAt: DateTime <<null: false>>
}

entity GroupMessageThreadGroup {
  id: ObjectId
  groupId: ObjectId
  groupThreadId: ObjectId
  createdAt: DateTime <<null: false>>
  updatedAt: DateTime <<null: false>>
}

entity GroupMessageThreadUserSeen {
  id: ObjectId
  userId: ObjectId
  groupThreadId: ObjectId
  lastSeenAt: DateTime
  createdAt: DateTime <<null: false>>
  updatedAt: DateTime <<null: false>>
}

entity SupportMessage {
  id: ObjectId
  content: String
  attachments: Attachment[]
  supportThreadId: ObjectId
  userId: ObjectId
  createdAt: DateTime <<null: false>>
  updatedAt: DateTime <<null: false>>
}

entity SupportMessageThreadStatusHistory {
  id: ObjectId
  status: int <<limit: 4>>
  threadId: ObjectId
  userId: ObjectId
  createdAt: DateTime <<null: false>>
  updatedAt: DateTime <<null: false>>
}

entity SupportMessageThread {
  id: ObjectId
  subject: String
  status: int <<limit: 4>>
  lastMessageAt: DateTime
  stepId: ObjectId
  processId: ObjectId
  userId: ObjectId
  claimedBy: ObjectId
  organizationId: ObjectId
  createdAt: DateTime <<null: false>>
  updatedAt: DateTime <<null: false>>
}

entity SupportMessageThreadUserSeen {
  id: ObjectId
  lastSeenAt: DateTime
  supportThreadId: ObjectId
  userId: ObjectId
  createdAt: DateTime <<null: false>>
  updatedAt: DateTime <<null: false>>
}

entity GroupProcess {
  id: ObjectId
  groupId: ObjectId
  processId: ObjectId
  createdAt: DateTime <<null: false>>
  updatedAt: DateTime <<null: false>>
}

entity UserProcess {
  id: ObjectId
  userId: ObjectId
  processId: ObjectId
  createdAt: DateTime <<null: false>>
  updatedAt: DateTime <<null: false>>
}

entity Process {
  id: ObjectId
  name: String <<limit: 255>>
  description: String <<limit: 65535>>
  startDate: DateTime
  endDate: DateTime
  createdBy: ObjectId
  image: String <<limit: 255>>
  totalTime: String <<limit: 255, default: "00:00:00">>
  organizationId: ObjectId
  collectionId: ObjectId
  status: String
  reason: String <<limit: 255>>
  primaryGroupId: ObjectId
  documentTypeId: ObjectId
  publishedDate: DateTime
  rejectedDate: DateTime
  rejectedById: ObjectId
  publishedById: ObjectId
  procedureType: String
  procedureIcon: String <<limit: 255>>
  procedureIconColor: String <<limit: 255>>
  isPublished: Boolean <<default: false>>
  version: String
  releaseNote: String
  editorNote: String
  createdAt: DateTime <<null: false>>
  updatedAt: DateTime <<null: false>>
}

entity Collection {
  id: ObjectId
  name: String <<limit: 255>>
  description: String
  mainMedia: String <<limit: 255>>
  overview: String <<limit: 65535>>
  public: Boolean <<default: true>>
  isVisible: Boolean <<default: true>>
  archivedAt: DateTime
  publishedDate: DateTime
  organizationId: ObjectId
  createdAt: DateTime <<null: false>>
  updatedAt: DateTime <<null: false>>
}

entity CollectionGroup {
  id: ObjectId
  position: int
  collectionId: ObjectId
  groupId: ObjectId
  createdAt: DateTime <<null: false>>
  updatedAt: DateTime <<null: false>>
}

entity CollectionProcess {
  id: ObjectId
  position: int
  collectionId: ObjectId
  processId: ObjectId
  createdAt: DateTime <<null: false>>
  updatedAt: DateTime <<null: false>>
}

entity UserCollection {
  id: ObjectId
  userId: ObjectId
  collectionId: ObjectId
  createdAt: DateTime <<null: false>>
  updatedAt: DateTime <<null: false>>
}

entity DocumentType {
  id: ObjectId
  name: String <<limit: 255>>
  description: String <<limit: 65535>>
  organizationId: ObjectId
  createdBy: ObjectId
  iconId: ObjectId
  createdAt: DateTime <<null: false>>
  updatedAt: DateTime <<null: false>>
}

entity Tag {
  id: ObjectId
  name: String <<limit: 255>>
  organizationId: ObjectId
  createdBy: ObjectId
  createdAt: DateTime <<null: false>>
  updatedAt: DateTime <<null: false>>
}

entity ProcessTag {
  processId: ObjectId
  tagId: ObjectId
  createdAt: DateTime <<null: false>>
  updatedAt: DateTime <<null: false>>
}

entity ProcessRating {
  review: String
  rating: int <<limit: 5>>
  userId: ObjectId
  processId: ObjectId
  createdBy: ObjectId
  createdAt: DateTime <<null: false>>
  updatedAt: DateTime <<null: false>>
}

entity Step {
  id: ObjectId
  name: String <<limit: 255>>
  time: String <<limit: 255>>
  position: int <<limit: 4>>
  archived: Boolean <<default: false>>
  processId: ObjectId
  iconId: ObjectId
  createdAt: DateTime <<null: false>>
  updatedAt: DateTime <<null: false>>
}

entity Block {
  id: ObjectId
  type: String <<limit: 255>>
  content: String <<limit: 16777215>>
  position: int <<limit: 4>>
  mediaTitle: String <<limit: 255>>
  isDisableMediaLabel: Boolean
  stepId: ObjectId
  processId: ObjectId
  mediaId: ObjectId
  iconId: ObjectId
  createdAt: DateTime <<null: false>>
  updatedAt: DateTime <<null: false>>
}

entity BlockMedia {
  id: ObjectId
  blockId: ObjectId
  mediaId: ObjectId
  createdAt: DateTime <<null: false>>
  updatedAt: DateTime <<null: false>>
}

entity DecisionPoint {
  id: ObjectId
  title: String <<limit: 255>>
  position: int
  blockId: ObjectId
  createdBy: ObjectId
  createdAt: DateTime <<null: false>>
  updatedAt: DateTime <<null: false>>
}

entity DecisionPointStep {
  id: ObjectId
  stepId: ObjectId
  decisionPointId: ObjectId
  createdAt: DateTime <<null: false>>
  updatedAt: DateTime <<null: false>>
}

entity DecisionPointMedia {
  id: ObjectId
  decisionPointId: ObjectId
  mediaId: ObjectId
  mediaTitle: String <<limit: 255>>
  createdAt: DateTime <<null: false>>
  updatedAt: DateTime <<null: false>>
}

entity Media {
  id: ObjectId
  name: String <<limit: 255>>
  image: String <<limit: 255>>
  document: String <<limit: 255>>
  position: int
  originalImage: String <<limit: 255>>
  url: String <<limit: 255>>
  videoThumbnailUrl: String <<limit: 255>>
  mediaType: String
  createdBy: ObjectId
  stepId: ObjectId
  originalFile: String <<limit: 255>>
  organizationId: ObjectId
  createdAt: DateTime <<null: false>>
  updatedAt: DateTime <<null: false>>
}

entity Favorite {
  id: ObjectId
  userId: ObjectId
  processId: ObjectId
  collectionId: ObjectId
  createdAt: DateTime <<null: false>>
  updatedAt: DateTime <<null: false>>
}


entity AuditTrail {
  id: ObjectId
  request: String
  response: String
  route: String
  status: String
  createdAt: DateTime <<null: false>>
  updatedAt: DateTime <<null: false>>
}

entity Notification {
  id: ObjectId
  title: String
  reason: String
  type: String
  deletedName: String
  subType: String
  rejectionReason: String
  description: String
  comment: String
  isSeen: Boolean
  reviewerId: ObjectId
  userId: ObjectId
  authorId: ObjectId
  processWorkflowId: ObjectId
  processId: ObjectId
  stepId: ObjectId
  messageThreadId: ObjectId
  createdBy: ObjectId
  organizationId: ObjectId
  createdAt: DateTime <<null: false>>
  updatedAt: DateTime <<null: false>>
}

entity Icon {
  id: ObjectId
  shape: String
  iconName: String
  color: String
  type: String
  description: String
  isDark: Boolean <<default: false>>
  isDefaultIcon: Boolean <<default: false>>
  organizationId: ObjectId
  createdAt: DateTime <<null: false>>
  updatedAt: DateTime <<null: false>>
}

Process ||..o{ GroupProcess
Process ||..o{ UserProcess
Process ||..o{ Step
Process ||..o{ CollectionProcess
Process ||..o{ ProcessTag
Process ||..o{ Favorite
Process ||..o{ Block
Process ||..o{ Notification
Process ||..o{ ProcessRating

Collection ||..o{ CollectionProcess
Collection }|..o{ Process
Collection ||..o{ CollectionGroup
Collection ||..o{ Favorite
Collection ||..o{ UserCollection

Step ||..o{ Media
Step ||..o{ Block
Step ||..o{ DecisionPointStep
Step ||..o{ Notification

Block ||..o{ DecisionPoint
Block ||..o{ BlockMedia

DecisionPoint ||..o{ DecisionPointStep
DecisionPoint ||..o{ DecisionPointMedia

Media ||..o{ Block
Media ||..o{ BlockMedia
Media ||..o{ DecisionPointMedia

Tag ||..o{ ProcessTag

DocumentType ||..o{ Process

Organization ||..o{ Collection
Organization ||..o{ DocumentType
Organization ||..o{ Tag
Organization ||..o{ Group
Organization ||..o{ Media
Organization ||..o{ Process
Organization ||..o{ Tag
Organization ||..o{ Notification
Organization ||..o{ Icon

User ||..o{ Process
User ||..o{ GroupMember
User ||..o{ Favorite
User ||..o{ UserProcess
User ||..o{ DecisionPoint
User ||..o{ DocumentType
User ||..o{ Media
User ||..o{ Notification
User ||..o{ GroupMessageThreadUserSeen
User ||..o{ ProcessRating
User ||..o{ UserCollection
User ||..o{ GroupMessage
User ||..o{ SupportMessage

GroupMessage ||..o{ Attachment
SupportMessage ||..o{ Attachment

Group ||..o{ GroupMember
Group ||..o{ GroupProcess
Group ||..o{ GroupMessageThreadGroup

GroupMessageThread ||..o{ GroupMessageThreadGroup
GroupMessageThread ||..o{ GroupMessageThreadUserSeen
GroupMessageThread ||..o{ GroupMessage

SupportMessageThread ||..o{ SupportMessage
SupportMessageThread ||..o{ SupportMessageThreadStatusHistory
SupportMessageThread ||..o{ SupportMessageThreadUserSeen

SupportMessageThread ||..|{ Notification

Icon |o--o{ Block
Icon |o--o{ Step
Icon |o--o{ DocumentType

@enduml
